version: "3.8"

services:
  backend:
    depends_on:
      - database
    image: node:12-alpine
    working_dir: /app
    volumes:
      - type: bind
        source: ./backend
        target: /app
    command: sh -c "yarn install && yarn start:dev"
    ports:
      - 5000:3000
  frontend:
    image: node:12-alpine
    working_dir: /app
    volumes:
      - type: bind
        source: ./frontend
        target: /app
    ports:
      - 3000:3000
    command: sh -c "yarn install && yarn start"
  database:
    image: library/postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: xalvaine
      POSTGRES_PASSWORD: example
      POSTGRES_DB: musicians
    volumes:
      - database:/var/lib/postgresql

volumes:
  database:
