services:
  backend:
    image: node:12-alpine
    working_dir: /app
    volumes:
      - type: bind
        source: ./backend
        target: /app
    command: sh -c "yarn install && yarn start:dev"
    ports:
      - 5000:3000
  frontend:
    image: node:12-alpine
    working_dir: /app
    volumes:
      - type: bind
        source: ./frontend
        target: /app
    ports:
      - 3000:3000
    command: sh -c "yarn install && yarn start"
