version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.prod.dockerfile
    command: sh -c "yarn start:prod"
    expose:
      - 3000
    ports:
      - 5000:3000
  frontend:
    volumes:
      - react-build:/home/frontend/build
    build:
      context: ./frontend
      dockerfile: frontend.prod.dockerfile

  nginx:
    depends_on:
      - frontend
      - backend
    volumes:
      - react-build:/build
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    image: nginx:stable-alpine
    entrypoint: nginx -g 'daemon off;'
    ports:
      - 3000:80

volumes:
  react-build:
