version: "3.8"

services:
  backend:
    image: node:12-alpine
    working_dir: /app
    volumes:
      - type: bind
        source: ./backend
        target: /app
    command: sh -c "yarn install && yarn start:dev"
    ports:
      - 5000:3000
  frontend:
    image: node:12-alpine
    working_dir: /app
    volumes:
      - type: bind
        source: ./frontend
        target: /app
    ports:
      - 3000:3000
    command: sh -c "yarn install && yarn start"
  database:
    restart: always
    image: sameersbn/postgresql:12-20200524
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - DB_USER=
      - DB_PASS=
      - DB_NAME=
      - DB_TEMPLATE=
      - DB_EXTENSION=
      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=
    command: "--wal_keep_segments=32 --logging_collector=off"
    volumes:
      - database:/var/lib/postgresql

volumes:
  database:
