version: "3.8"

services:
  backend:
    depends_on:
      - database
    build:
      context: ./backend
      dockerfile: backend.prod.dockerfile
    command: sh -c "yarn start:prod"
    expose:
      - 3000
    env_file:
      - .env

  frontend:
    depends_on:
      - backend
    volumes:
      - react-build:/home/frontend/build
    build:
      context: ./frontend
      dockerfile: frontend.prod.dockerfile

  nginx:
    depends_on:
      - frontend
    volumes:
      - react-build:/build
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    image: nginx:stable-alpine
    entrypoint: nginx -g 'daemon off;'
    ports:
      - 3000:80

  database:
    image: library/postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - database:/var/lib/postgresql
    env_file:
      - .env

volumes:
  react-build:
  database:
